@startuml

class Product {
  - id: Long
  - name: String
  - price: double

  + Product()
  + Product)id: Long, name: String, double

  + getId() : Long
  + getName() : String
  + get Price() : double
}

@enduml